INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Abu-Bakar.Musayev@gmail.com', 'qwerty007', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Albina.Arushanian@yahoo.com', 'qwerty008', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Dmytro.Sainozhenko@bing.com', 'qwerty009', 'MANAGER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Edgar.Arushanyan@email.com ', 'qwerty010', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Ekaterina.Zakozhurnikova@icloud.com', 'qwerty011', 'MANAGER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Irene.Steitz@mail.de', 'qwerty012', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Joseph.Hafizi@mail.de', 'qwerty013', 'USER', 'NOT_CONFIRMED');
