INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Abu-Bakar.Musayev@gmail.com', 'qwerty007', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Albina.Arushanian@yahoo.com', 'qwerty008', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Dmytro.Sainozhenko@bing.com', 'qwerty009', 'MANAGER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Edgar.Arushanyan@email.com ', 'qwerty010', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Ekaterina.Zakozhurnikova@icloud.com', 'qwerty011', 'MANAGER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Irene.Steitz@mail.de', 'qwerty012', 'USER', 'NOT_CONFIRMED');
INSERT INTO ACCOUNT (EMAIL, PASSWORD, ROLE, STATE)
VALUES ('Joseph.Hafizi@mail.de', 'qwerty013', 'USER', 'NOT_CONFIRMED');

INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2023-08-15', 'Публикация 1', 4, 'PUBLISHED');
INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2023-08-25', 'Публикация 2', 4, 'DRAFT');
INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2024-05-22', 'Публикация 3', 7, 'PUBLISHED');
INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2023-08-31', 'Публикация 4', 7, 'DELETED');
INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2021-07-15', 'Публикация 5', 10, 'PUBLISHED');
INSERT INTO ARTICLE (PUBLISH_DATE, TEXT, ABOUT_ID, STATE)
VALUES ('2021-07-06', 'Публикация 6', 10, 'DELETED');

